### ISSUE TITLE
Matching Python code: saving in hdf5

### ISSUE THREAD

**Issue by paugier** [turbulencelyon/4d-ptv#7]
The C++ code can save its output in hdf5 files. With h5py, it's very easy to do in Python so the Python code should also save its output in hdf5 files.

**Comment by ddumont-2607** [comment]
Indeed, we upgraded the C++ code to save its outputs in hdf5 files but we did not do that for Python code. It has to be done so feel free to do it! The best should be to save output with the same convention in the 2 codes.

**Comment by jsalort** [comment]
This GitHub history is not complete because we switched relatively recently.
I added the HDF5 support to the C++ code when I modified that code to solve issues that were raised during the internship of Elian Bernard last year. I didn't add the support to the Python version at that time, because it was so much slower than the C++ version that it did not seem useful (we were using the C++ code instead). Of course, now that the Python version is up to speed thanks to your work, support for HDF5 should be added (and this should be trivial to do).
